# Generated by Django 4.1.7 on 2023-03-25 15:32

import acornmoodtracker.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=90, primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=90)),
                ('lastname', models.CharField(max_length=90)),
                ('email', models.CharField(max_length=90)),
                ('phone', models.CharField(max_length=90)),
            ],
        ),
        migrations.CreateModel(
            name='Mood',
            fields=[
                ('moodID', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=90)),
                ('notes', models.TextField(max_length=2000)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('squirrel', models.CharField(choices=[(0, 'Happy'), (1, 'Sad'), (2, 'Angry'), (3, 'Confused'), (4, 'Hopeful')], max_length=90)),
                ('username', models.ForeignKey(default=acornmoodtracker.models.User.get_default_pk, on_delete=django.db.models.deletion.CASCADE, to='acornmoodtracker.user')),
            ],
        ),
        migrations.CreateModel(
            name='Feeling',
            fields=[
                ('feelingID', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=90)),
                ('parentMoodID', models.ForeignKey(default=acornmoodtracker.models.Mood.get_default_pk, on_delete=django.db.models.deletion.CASCADE, to='acornmoodtracker.mood')),
            ],
        ),
    ]
